# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhilipMovieDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhilipMovieDB
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'NSObject+Rx'
    pod 'RxDataSources'
    pod 'RxOptional'
    pod 'Moya/RxSwift'
    pod 'SDWebImage'
    pod 'SwiftGifOrigin'
    pod 'FLEX', :configurations => ['Debug']

  target 'PhilipMovieDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhilipMovieDBUITests' do
    # Pods for testing
  end

end
